spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    hibernate.ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2Ldflwfnm0
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: mycrudapp
    password: wdgsfjfagulixoqc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
messages:
  b-day-notification-period: 5


