spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    hibernate.ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2Ldflwfnm0
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE